// packages/main/integrations/nuxt/app/components/BookList.vue
<script setup lang="ts">
import type { StoredBook } from '~/lib/types'

const props = defineProps<{
  books: StoredBook[]
}>()

const emit = defineEmits<{
  error: [message: string]
  refresh: []
}>()

const groups = useGroupedBooks(computed(() => props.books))

function onRemoved() {
  emit('refresh')
}

function onError(msg: string) {
  emit('error', msg)
}
</script>

<template>
  <div>
    <section v-for="group in groups" :key="group.genre" class="mb-6">
      <h2 class="mb-2 text-sm font-medium uppercase tracking-wide text-zinc-400">
        {{ group.genre }}
      </h2>
      <ul class="space-y-1">
        <li v-for="book in group.books" :key="book.id" class="flex items-center text-sm">
          <span>
            <strong>{{ book.title }}</strong> · {{ book.author }}
            <span class="ml-2 text-zinc-400">ISBN {{ book.isbn }}</span>
          </span>
          <RemoveButton
            :book-id="book.id"
            @error="onError"
            @removed="onRemoved"
          />
        </li>
      </ul>
    </section>
  </div>
</template>

// packages/main/integrations/nextjs/app/collection/_components/book-list.tsx
'use client'

import { useGroupedBooks } from '../../hooks/use-grouped-books'
import type { StoredBook } from '../../lib/types'
import RemoveButton from './remove-button'

export default function BookList({ books, onError }: { books: StoredBook[]; onError?: (msg: string) => void }) {
  const groups = useGroupedBooks(books)

  return (
    <>
      {groups.map(({ genre, books: sorted }) => (
        <section key={genre} className="mb-6">
          <h2 className="mb-2 text-sm font-medium uppercase tracking-wide text-zinc-400">
            {genre}
          </h2>
          <ul className="space-y-1">
            {sorted.map((book) => (
              <li key={book.id} className="flex items-center text-sm">
                <span>
                  <strong>{book.title}</strong> · {book.author}
                  <span className="ml-2 text-zinc-400">ISBN {book.isbn}</span>
                </span>
                <RemoveButton bookId={book.id} onError={onError} />
              </li>
            ))}
          </ul>
        </section>
      ))}
    </>
  )
}
