// packages/main/integrations/react/src/components/alert-banner.tsx
import type { ReactNode } from 'react'

type Variant = 'error' | 'success'

const styles: Record<Variant, string> = {
  error: 'rounded bg-red-50 p-3 text-sm text-red-700',
  success: 'rounded bg-green-50 p-3 text-sm text-green-700',
}

export function AlertBanner({ variant = 'error', children }: { variant?: Variant; children: ReactNode }) {
  if (!children) return null
  return <div className={styles[variant]} role="alert">{children}</div>
}

// packages/main/integrations/nuxt/app/components/AlertBanner.vue
<script setup lang="ts">
withDefaults(defineProps<{
  variant?: 'error' | 'success'
}>(), {
  variant: 'error',
})

const slots = useSlots()
</script>

<template>
  <div
    v-if="slots.default"
    role="alert"
    :class="variant === 'success'
      ? 'rounded bg-green-50 p-3 text-sm text-green-700'
      : 'rounded bg-red-50 p-3 text-sm text-red-700'"
  >
    <slot />
  </div>
</template>
